// Generated by Website Factory (GaLaBau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "gartenneugestaltung"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege"
  | "zaun-sichtschutz"
  | "bewaesserung"
  | "baumpflege"
  | "gewerbeflaechen";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "Allee Garten- und Landschaftsbau",
    "city": "Mannheim",
    "foundedYear": "",
    "teamSize": "",
    "machines": ""
  },
  "claim": "Pflaster, Terrassen und Baumfällung in Mannheim.",
  "heroSubline": "Von der Einfahrt über den Gabionenzaun bis zum Heckenschnitt. Ein Team, feste Bauzeit, geräumte Baustelle. Einsatzgebiet: Mannheim, Ludwigshafen, Heidelberg und rund 40 km Umkreis.",
  "services": [
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflasterarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Einfahrten, Höfe und Wege: alter Belag raus, Unterbau neu, Fläche sauber verlegt und verfugt.",
      "intro": "Pflaster hält so lange, wie der Unterbau es zulässt. Bei einem Hof in der Umgebung haben wir den alten Betonboden komplett entfernt, den Bodenaufbau erneuert, ein Fundament gesetzt und erst danach neu gepflastert. Genau diese Reihenfolge entscheidet, ob eine Fläche nach fünf Jahren noch eben liegt.",
      "bullets": [
        "Einfahrt, Hof, Gehweg und Terrassenflächen in Beton- oder Naturstein",
        "Rückbau von altem Beton oder gesetztem Pflaster inklusive Entsorgung",
        "Tragschicht nach Belastung: PKW, Wohnmobil oder Lieferverkehr",
        "Gefälle, Rinnen und Anschluss an Bestandsflächen werden vorab geplant",
        "Randeinfassungen, Fundamente und Mauern kommen aus demselben Team"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Quadratmeter grob schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Aufbau festlegen",
          "text": "Wir klären Belastung, Untergrund und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Aushub, Entsorgung, Tragschicht, Material und Einbau stehen als getrennte Positionen darin."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln, Verfugen und ein geräumter Platz zum Schluss."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder Versickerung ein."
        }
      ],
      "image": "/assets/leistungen/pflasterarbeiten-terrasse.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 3000
      },
      "seo": {
        "title": "Pflasterarbeiten in Mannheim | Allee Garten- und Landschaftsbau",
        "description": "Pflasterarbeiten für Einfahrt, Hof und Wege in Mannheim: alter Belag raus, tragfähiger Unterbau, geplante Entwässerung, saubere Randeinfassung."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassenbau",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen aus Betonstein, Naturstein, Keramik oder Holz, vom Unterbau bis zum Randabschluss.",
      "intro": "Auch eine kleine Terrasse von drei mal drei Metern braucht denselben Unterbau wie eine große: tragfähig, im Gefälle, sauber eingefasst. Wir bauen beides, vom kompakten Sitzplatz im Fischgrätverband bis zur durchgehenden Fläche am Haus.",
      "bullets": [
        "Beton- und Natursteinpflaster, Platten, Keramik, Holz und WPC",
        "Unterbau im Splittbett, auf Stelzlagern oder auf Punktfundamenten",
        "Randabschluss mit Betonkantenstein oder Naturstein statt loser Kante",
        "Anschlusshöhen an Türschwelle und Rasen werden vor dem Bau festgelegt",
        "Übergang zu Rasen, Beet oder Rasengittersteinen gleich mitgebaut"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonnenstand und gewünschtes Material, gern mit Inspirationsbildern."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir sehen uns Anschlusshöhen, Türschwellen und die Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Aufbau, Material und Zusatzleistungen getrennt kalkuliert, mit Mengen."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und gemeinsame Abnahme."
        }
      ],
      "faq": [
        {
          "q": "Pflaster, Platte oder Holz?",
          "a": "Holz ist warm und lebendig, braucht aber Pflege. Beton- und Naturstein sind pflegeleicht und farbstabil. Wir zeigen beides an realen Flächen, bevor Sie sich festlegen."
        },
        {
          "q": "Lohnt sich das auch bei einer kleinen Fläche?",
          "a": "Ja, kleine Sitzplätze bauen wir regelmäßig. Der Aufwand für Aushub und Unterbau bleibt anteilig höher als bei großen Flächen, das sagen wir vorab statt hinterher."
        }
      ],
      "image": "/assets/leistungen/terrassenbau-grossformatplatten-01.webp",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassenbau in Mannheim | Allee Garten- und Landschaftsbau",
        "description": "Terrassenbau in Mannheim mit Pflaster, Naturstein, Keramik oder Holz: tragfähiger Unterbau, Gefälle, sauberer Randabschluss."
      }
    },
    {
      "key": "baumpflege",
      "slug": "baumpflege",
      "label": "Baumfällung & Baumpflege",
      "navLabel": "Baum",
      "cta": "Baum ansehen lassen",
      "unit": "stk",
      "teaser": "Fällung, Rückschnitt und Kronenpflege, auch wenn der Baum eng am Haus oder an Leitungen steht.",
      "intro": "Ein großer Ahorn im Reihenhausgarten oder Tannen, die in eine Starkstromleitung gewachsen sind: solche Bäume nehmen wir stückweise ab, statt sie zu werfen. Das dauert länger, schont aber Dach, Zaun und Beet darunter.",
      "bullets": [
        "Fällung in Teilstücken, wenn kein Fallraum vorhanden ist",
        "Rückschnitt, Kronenpflege und Einkürzen von Sträuchern",
        "Abstimmung mit dem Netzbetreiber, wenn Leitungen im Weg sind",
        "Zäune und Bauteile werden bei Bedarf ab- und wieder aufgebaut",
        "Abtransport von Stamm, Ästen und Schnittgut gehört dazu"
      ],
      "ablauf": [
        {
          "title": "Foto schicken",
          "text": "Ein Bild vom ganzen Baum und vom Standort reicht für die erste Einschätzung."
        },
        {
          "title": "Vor Ort prüfen",
          "text": "Wir klären Fallraum, Zugang, Leitungen und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Fällung, Rückschnitt, Entsorgung und gegebenenfalls Stubbenfräsen getrennt ausgewiesen."
        },
        {
          "title": "Ausführung",
          "text": "Absperren, abtragen, aufräumen. Der Platz ist am selben Tag wieder frei."
        }
      ],
      "faq": [
        {
          "q": "Darf ich meinen Baum überhaupt fällen?",
          "a": "Das hängt von der Baumschutzsatzung der Gemeinde und von der Art und dem Stammumfang ab. Wir sagen Ihnen vor der Beauftragung, ob eine Genehmigung nötig ist, einholen müssen Sie sie als Eigentümer."
        },
        {
          "q": "Wann darf geschnitten werden?",
          "a": "Starke Rückschnitte und Fällungen sind vom 1. März bis 30. September gesetzlich eingeschränkt. Schonende Pflegeschnitte und Gefahrenfälle sind davon ausgenommen, das prüfen wir im Einzelfall."
        }
      ],
      "image": "/assets/leistungen/baumpflege-klettertechnik.webp",
      "estimate": {
        "minPerUnit": 250,
        "maxPerUnit": 1200,
        "baseMin": 600
      },
      "seo": {
        "title": "Baumfällung & Baumpflege in Mannheim | Allee Garten- und Landschaftsbau",
        "description": "Baumfällung und Baumpflege in Mannheim: Abtragen in Teilstücken bei engem Stand, Rückschnitt, Kronenpflege und Abtransport des Schnittguts."
      }
    },
    {
      "key": "zaun-sichtschutz",
      "slug": "zaun-sichtschutz",
      "label": "Zaun & Sichtschutz",
      "navLabel": "Zaun",
      "cta": "Sichtschutz anfragen",
      "unit": "lfm",
      "teaser": "Gabionen, Doppelstabmatten und Aluminiumpaneele mit Tor, kalkuliert nach laufenden Metern.",
      "intro": "Gabionen mit eingesetzten Paneelen sind eine unserer meistgebauten Anlagen: die Steinkörbe nehmen die Höhe auf, die dunklen Paneele bringen den blickdichten Teil. Entscheidend sind Fundament, Grenzverlauf und ein Sockel, der den Höhenunterschied zur Straße abfängt.",
      "bullets": [
        "Gabionen, Doppelstabmatten, Aluminium, Holz und WPC",
        "Kalkulation nach laufenden Metern inklusive Pfosten und Fundament",
        "Sockel und Stützmauern aus Naturstein oder Betonblocksteinen",
        "Tore und Gartentüren mit passender Beschlagtechnik",
        "Hinweise zu Grenzbebauung, Höhe und örtlicher Satzung vorab"
      ],
      "ablauf": [
        {
          "title": "Meter schätzen",
          "text": "Grobe Länge und gewünschte Höhe genügen für die erste Einordnung."
        },
        {
          "title": "Grenze klären",
          "text": "Wir prüfen Verlauf, Untergrund, Höhenversprung und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Material, Pfosten, Fundamente, Sockel und Tore als getrennte Positionen."
        },
        {
          "title": "Montage",
          "text": "Fundamente setzen, ausrichten, Körbe füllen, montieren, Baustelle räumen."
        }
      ],
      "faq": [
        {
          "q": "Wie hoch darf der Sichtschutz sein?",
          "a": "Das regeln Landesrecht und örtliche Satzung, häufig sind an der Grenze rund 1,80 m ohne Genehmigung möglich. Wir prüfen den konkreten Fall vor der Montage."
        },
        {
          "q": "Brauche ich Fundamente?",
          "a": "Bei Gabionen, Sichtschutzwänden und Toren ja. Bei leichten Zäunen genügen oft Einschlaghülsen, das entscheidet der Untergrund."
        }
      ],
      "image": "/assets/leistungen/zaun-und-sichtschutz.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 320,
        "baseMin": 1200
      },
      "seo": {
        "title": "Zaun & Sichtschutz in Mannheim | Allee Garten- und Landschaftsbau",
        "description": "Zaun und Sichtschutz in Mannheim nach laufenden Metern: Gabionen mit Paneelen, Doppelstabmatten, Tore, Fundamente und Sockelmauern."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege",
      "navLabel": "Pflege",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Hecken, Sträucher und Rasen: einmalig, wenn es zu viel geworden ist, oder fest über die Saison.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart den jährlichen Rückschnitt-Notfall. Beim Heckenschnitt sehen wir uns die Hecke vorher an: Wo ein Vogelnest sitzt, wird der Abschnitt abgedeckt und später nachgearbeitet, statt ihn einfach mitzunehmen.",
      "bullets": [
        "Heckenschnitt, Formschnitt und Rückschnitt von Sträuchern",
        "Rasenpflege: Mähen, Vertikutieren, Nachsaat, Düngung",
        "Rollrasen und Kunstrasen verlegen, inklusive Vorbereitung des Bodens",
        "Einmalpflege für verwilderte Gärten inklusive Entsorgung",
        "Pflegevertrag mit festen Terminen über die Saison"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmalig oder Vertrag, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen, wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet ein Pflegevertrag?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Jahresbetrag."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind vom 1. März bis 30. September nicht zulässig, und brütende Vögel in der Hecke sind immer geschützt."
        }
      ],
      "image": "/assets/leistungen/gartenpflege-heckenschnitt.webp",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege in Mannheim | Allee Garten- und Landschaftsbau",
        "description": "Gartenpflege in Mannheim als Einmalpflege oder Pflegevertrag: Heckenschnitt, Rasenpflege, Rollrasen und Abtransport des Schnittguts."
      }
    },
    {
      "key": "gartenneugestaltung",
      "slug": "gartenneugestaltung",
      "label": "Gartenneugestaltung",
      "navLabel": "Gartengestaltung",
      "cta": "Projekt planen lassen",
      "unit": "qm",
      "teaser": "Wenn Hof oder Garten komplett neu soll: Rückbau, Erdarbeiten, Mauern, Wege, Terrasse und Bepflanzung.",
      "intro": "Eine Neugestaltung ist selten nur Bepflanzung. Meist gehören Rückbau, Aushub, eine Stützmauer und die Entwässerung dazu, bevor überhaupt ein Stein liegt. Weil Erdarbeiten, Mauerbau, Pflaster und Pflanzung bei uns aus demselben Team kommen, muss niemand zwischen Gewerken vermitteln.",
      "bullets": [
        "Aufmaß vor Ort, Bestandsaufnahme von Boden, Gefälle und Zufahrt",
        "Erdarbeiten und Aushub, Rückbau und Entsorgung des alten Belags",
        "Stützmauern und Fundamente aus Betonblockstein oder Naturstein",
        "Wege, Terrasse, Beete, Rollrasen und Bewässerung aus einer Hand",
        "Teich- und Natursteinarbeiten auf Wunsch im selben Zug"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern Fläche, Zustand und Wunsch über den Projekt-Assistenten, idealerweise mit Fotos."
        },
        {
          "title": "Termin vor Ort",
          "text": "Wir messen auf, prüfen Zufahrt, Boden und Gefälle und klären, was baulich sinnvoll ist."
        },
        {
          "title": "Planung & Angebot",
          "text": "Sie bekommen eine nachvollziehbare Aufstellung mit Positionen, nicht nur eine Endsumme."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, ein Ansprechpartner, saubere Übergabe inklusive Pflegehinweisen."
        }
      ],
      "faq": [
        {
          "q": "Was kostet eine Gartenneugestaltung?",
          "a": "Das hängt stark von Fläche, Untergrund, Zufahrt und Material ab. Deshalb nennen wir online nur grobe Orientierungsrahmen und den verbindlichen Preis erst nach dem Aufmaß vor Ort."
        },
        {
          "q": "Wie lange dauert so ein Projekt?",
          "a": "Kleinere Umgestaltungen dauern wenige Tage, ein kompletter Hof mit Rückbau, Mauer und Pflaster meist mehrere Wochen. Den Zeitrahmen legen wir vor Baubeginn fest."
        }
      ],
      "image": "/assets/leistungen/gartenneugestaltung-mit-beleuchtung.webp",
      "estimate": {
        "minPerUnit": 120,
        "maxPerUnit": 320,
        "baseMin": 4000
      },
      "seo": {
        "title": "Gartenneugestaltung in Mannheim | Allee Garten- und Landschaftsbau",
        "description": "Garten und Hof neu gestalten in Mannheim: Rückbau, Erdarbeiten, Stützmauern, Wege, Terrasse und Bepflanzung aus einer Hand."
      }
    },
    {
      "key": "bewaesserung",
      "slug": "bewaesserung",
      "label": "Bewässerung",
      "navLabel": "Bewässerung",
      "cta": "Bewässerung prüfen",
      "unit": "qm",
      "teaser": "Automatische Bewässerung für Rasen und Beete, inklusive Steuerung und Wartung.",
      "intro": "Eine automatische Bewässerung spart Wasser, weil sie früh morgens und nach Bedarf läuft. Wichtig ist die Auslegung: Druck, Durchfluss und Kreise müssen zusammenpassen, sonst wird die Fläche ungleich versorgt.",
      "bullets": [
        "Planung nach Druck, Durchfluss und Flächenzuschnitt",
        "Getrennte Kreise für Rasen, Beete und Tropfbewässerung",
        "Steuerung mit Regensensor oder App-Anbindung",
        "Leitungen werden bei Neuanlagen vor dem Belag mitverlegt",
        "Wartung: Frühjahrsinbetriebnahme und Einwintern"
      ],
      "ablauf": [
        {
          "title": "Fläche & Wasser",
          "text": "Wir brauchen Flächengröße sowie Druck und Durchfluss am Hausanschluss."
        },
        {
          "title": "Auslegung",
          "text": "Kreise, Regner und Tropflinien werden auf die Fläche gerechnet."
        },
        {
          "title": "Angebot",
          "text": "Material, Verlegung und Steuerung transparent aufgeschlüsselt."
        },
        {
          "title": "Einbau",
          "text": "Verlegen, Einregulieren, Programmierung und Einweisung."
        }
      ],
      "faq": [
        {
          "q": "Muss der Rasen dafür raus?",
          "a": "Bei einer Nachrüstung nicht komplett. Die Leitungen kommen in schmale Schlitze, die in der Regel innerhalb weniger Wochen zuwachsen."
        },
        {
          "q": "Was kostet die Wartung?",
          "a": "Inbetriebnahme und Einwintern sind planbare Pauschalen, die wir mit dem Angebot ausweisen."
        }
      ],
      "image": "/assets/leistungen/bewaesserung-rasen-und-beete.webp",
      "estimate": {
        "minPerUnit": 12,
        "maxPerUnit": 35,
        "baseMin": 1800
      },
      "seo": {
        "title": "Bewässerung in Mannheim | Allee Garten- und Landschaftsbau",
        "description": "Automatische Bewässerung in Mannheim: Planung nach Druck und Durchfluss, getrennte Kreise, Steuerung, Nachrüstung und Wartung."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Mannheim",
    "radiusKm": 40,
    "note": "Wir arbeiten im Umkreis von rund 40 km um Mannheim, von Ludwigshafen und Speyer bis Heidelberg und Weinheim. Weiter entfernte Anfragen nehmen wir an, sagen aber ehrlich ab, wenn sich die Anfahrt für die Projektgröße nicht rechnet.",
    "plzPrefixes": [
      "68",
      "67",
      "69"
    ],
    "borderPlzPrefixes": [
      "64",
      "74",
      "76"
    ],
    "places": [
      "Mannheim-Rheinau",
      "Mannheim-Neckarau",
      "Ludwigshafen",
      "Schwetzingen",
      "Heidelberg",
      "Speyer",
      "Viernheim",
      "Hockenheim",
      "Brühl",
      "Ketsch",
      "Ladenburg",
      "Weinheim"
    ],
    "center": {
      "lat": 49.43502,
      "lng": 8.5254659
    }
  },
  "contact": {
    "phone": "0176 63610209",
    "phoneLink": "tel:+4917663610209",
    "whatsapp": "0176 63610209",
    "whatsappLink": "https://wa.me/4917663610209",
    "whatsappPrefill": "Hallo Allee Garten- und Landschaftsbau, ich habe eine Frage zu einem Gartenprojekt in ",
    "email": "",
    "leadEmail": ""
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 2500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Boden, Unterbau, Zufahrt, Entwässerung, Material und Ausführung ab und steht erst nach dem Aufmaß vor Ort fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 – 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 – 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 – 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Landschaftsgärtner, Helfer oder Quereinsteiger?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Wir sind ein kleines Team aus Mannheim-Rheinau und bauen zwischen Ludwigshafen, Heidelberg und Speyer. Pflaster, Terrassen, Gabionen, Baumfällung: Wer bei uns mitarbeitet, begleitet ein Projekt vom Aushub bis zur Abnahme, statt monatelang dieselbe Handreichung zu machen. Schicken Sie das Formular ab, den Rest klären wir am Telefon.",
    "roles": [
      "Landschaftsgärtner/in",
      "Pflasterer/in",
      "Helfer/in Garten- und Landschaftsbau",
      "Quereinsteiger/in"
    ],
    "benefits": [
      "Kurze Anfahrten: Die meisten Baustellen liegen keine 30 Minuten von Rheinau entfernt",
      "Feste Teams, die ein Projekt von der ersten bis zur letzten Stunde begleiten",
      "Werkzeug, Maschinen und Arbeitskleidung werden gestellt",
      "Pünktlicher Lohn, aufgeschriebene Überstunden, verlässlicher Feierabend"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Geräumte Baustelle",
        "text": "Schnittgut, Aushub und alter Belag gehen mit. Am Feierabend ist der Platz frei, nicht erst am Projektende."
      },
      {
        "label": "Preis nach dem Aufmaß",
        "text": "Erst die Fläche ansehen, dann ein Angebot mit getrennten Positionen für Aushub, Unterbau, Material und Einbau."
      },
      {
        "label": "Ein Ansprechpartner",
        "text": "Sie reden vom ersten Anruf bis zur Abnahme mit denselben Leuten, die auch auf der Baustelle stehen."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
