// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 37,
  "reviews": [
    {
      "author": "Stephanie Cleres-Henel",
      "rating": 5,
      "text": "Top Service und super Preis-Leistungs-Verhältnis! Dieser Gartenbaubetrieb hat bei uns einen sehr großen Ahornbaum gefällt. Von der Absprache bis zur Durchführung lief alles perfekt. Das Team arbeitet extrem schnell, sicher und hinterlässt den Arbeitsplatz absolut sauber. Die Preiskalkulation war fair und transparent. Wir können diese Firma jedem nur wärmstens weiterempfehlen! Familie Henel/Cleres-Henel",
      "time": "vor 3 Monaten"
    },
    {
      "author": "Tim-Philipp Schulz",
      "rating": 5,
      "text": "Wir sind mit den ausgeführten Arbeiten sehr zufrieden. Bei unserem Projekt wurde unser alter Hof, der durch den in die Jahre gekommenen Betonboden und den alten Holzzaun nicht mehr besonders ansprechend aussah, komplett neugestaltet. Der alte Beton wurde fachgerecht entfernt, der Bodenaufbau erneuert, ein Fundament erstellt, eine Mauer gesetzt und anschließend der Hof neu gepflastert.\nVon der ersten Beratung bis zur Fertigstellung hat alles hervorragend funktioniert. Die Kommunikation war jederzeit freundlich, transparent und zuverlässig. Das gesamte Team arbeitete pünktlich, sauber und sehr professionell. Man merkt, dass hier erfahrene Fachleute am Werk sind, die großen Wert auf Qualität legen.\nWir können diese Firma uneingeschränkt weiterempfehlen und werden bei zukünftigen Arbeiten gerne wieder auf sie zurückkommen.\nVielen Dank an das gesamte Team für die tolle Arbeit!",
      "time": "vor 3 Monaten"
    },
    {
      "author": "Christina Beddingfield",
      "rating": 5,
      "text": "Die Firma hat in unserem Garten mit fachlicher Kompetenz 2 riesengroße Tannen gefällt , die in Starkstromleitungen hineingewachsen waren. Auch das Fällen und Rückschritt  weitere Bäume wurde problemlos und präzise durchgeführt. Auch das teilweise Ab- und wieder Aufbauen unseres Gartenzauns wurde höchst professionell erledigt.\nFreundliche und prompte Kommunikation.\nAuch mit dem Preis-Leistungsverhältnis waren wir sehr zufrieden.\nGerne empfehle ich diese Firma weiter.",
      "time": "vor einem Monat"
    },
    {
      "author": "Anette",
      "rating": 5,
      "text": "Ich bin absolut begeistert und kann dieses Team von Herzen weiterempfehlen! 🌿\n\nBei mir wurde eine 3x3 Meter große Terrasse gebaut – und was soll ich sagen: Es ist einfach ein Traum geworden. Von der ersten Kontaktaufnahme bis zur finalen Umsetzung war alles rundum professionell, zuverlässig und unglaublich angenehm.\n\nDas gesamte Team war nicht nur fachlich top, sondern auch menschlich einfach großartig. Die Mitarbeiter waren freundlich, respektvoll und haben eine ruhige, positive Atmosphäre mitgebracht, sodass man sich während der gesamten Arbeiten jederzeit wohlgefühlt hat.\n\nDie Ausführung der Terrasse ist auf höchstem Niveau: sauber, präzise und mit viel Liebe zum Detail. Man merkt sofort, dass hier mit Erfahrung, Sorgfalt und echter Leidenschaft gearbeitet wird.\n\nIch bin mehr als glücklich mit dem Ergebnis und freue mich jeden Tag über meine neue Terrasse. Ein großes Dankeschön für diese tolle Arbeit – ich würde euch jederzeit wieder beauftragen!",
      "time": "vor 4 Monaten"
    },
    {
      "author": "zhang秋颖",
      "rating": 5,
      "text": "Sie haben meine Hecken geschnitten und dabei sehr sorgfältig und gewissenhaft gearbeitet. Als sie ein Vogelnest entdeckten, haben sie extra eine Abdeckung dafür angebracht. Sowohl der Chef als auch die Mitarbeiter sind sehr nett, sie besprechen alles ausführlich mit den Kunden und schlagen passende Lösungen vor. Die Preise sind zudem sehr angemessen.",
      "time": "vor 2 Monaten"
    }
  ]
};
